### ISSUE TITLE
What is the `mo` command?

### ISSUE THREAD

**Issue by elimisteve** [P5vc/ServerConfigurations#2]
Seems to be required. Thanks!

**Comment by P5vc** [comment]
Great question! Thanks for reaching out! We do have a short explanation in the documentation for Fetch Apply on line 365 (at the end of the [Modules section](https://github.com/P5vc/FetchApply/blob/main/README.md#modules)), which I'll paste below for you:

> Note: Fetch Apply comes bundled with `mo` by default (and it is sourced automatically, so there is no need to `source mo` in your `apply` file). This allows you to use mustache-style templates with your modules, as demonstrated above. For information on how to format these templates, see the [mo documentation](https://github.com/tests-always-included/mo "mo documentation").

This explanation is very basic, however, and undoubtedly hidden amongst all of the other, important information surrounding it! To provide a bit more useful overview, you can think of mo like a more-powerful version of the `cat` command. It is commonly used to read configuration files provided within an operations repository, and then write them to the desired location on a given system.

To write a simple configuration file to a desired location, all of the following commands would accomplish the same goal:

`cp example.conf /etc/example.conf`
`cat example.conf > /etc/example.conf`
`mo example.conf > /etc/example.conf`

However where `mo` differs from `cat`, is that it allows for more-advanced mustache-style templates to be used. These templates can contain variables, loop over arrays, and more.

Because `mo`is automatically sourced and fairly efficient, we use it for all of our modules that require configuration files to be written. Even if that module doesn't necessarily take advantage of the more-advanced features `mo` offers, we still use it for consistency purposes. That being said, it is definitely not required, and you could use one of the alternative commands listed above if you don't need the templating features of `mo`, to get the same result.

I hope that helps to answer your question and provides a bit more clarity!

**Comment by P5vc** [comment]
I haven't heard back, so I'm going to assume it's safe to go ahead and close this issue. Don't hesitate to reopen it if you have any further questions. Thank you!
